"""Deterministic workflow state and guard primitives for schema version 2.0."""

from .guards import (
    Accounting,
    ConcurrencyConfig,
    FailureKind,
    GuardViolation,
    JobAttempt,
    JobType,
    LogicalJobKey,
    RecoveryAction,
    RecoverySnapshot,
    RetryDecision,
    ensure_critic_dispatch_eligible,
    ensure_reader_dispatch_eligible,
    ensure_reviewer_barrier,
    ensure_single_logical_job_scope,
    next_attempt,
    recovery_actions,
)
from .service import ReviewAcceptanceDecision, ReviewReportStatus, WorkflowService
from .state import (
    AgentRunState,
    InvestigationState,
    InvalidTransition,
    PaperState,
    can_transition_agent_run,
    can_transition_investigation,
    can_transition_paper,
    transition_agent_run,
    transition_investigation,
    transition_paper,
)

__all__ = [
    "Accounting",
    "AgentRunState",
    "ConcurrencyConfig",
    "FailureKind",
    "GuardViolation",
    "InvestigationState",
    "InvalidTransition",
    "JobAttempt",
    "JobType",
    "LogicalJobKey",
    "PaperState",
    "RecoveryAction",
    "RecoverySnapshot",
    "RetryDecision",
    "ReviewAcceptanceDecision",
    "ReviewReportStatus",
    "WorkflowService",
    "can_transition_agent_run",
    "can_transition_investigation",
    "can_transition_paper",
    "ensure_critic_dispatch_eligible",
    "ensure_reader_dispatch_eligible",
    "ensure_reviewer_barrier",
    "ensure_single_logical_job_scope",
    "next_attempt",
    "recovery_actions",
    "transition_agent_run",
    "transition_investigation",
    "transition_paper",
]
